// ============================================================================
// Teams & Chat Mock Data — realistic demo data for UI development
// ============================================================================

import type {
  Team,
  Channel,
  TeamMember,
  ChatMessage,
  DirectMessage,
  ChatNotification,
  ChatTask,
} from "./chat-types";

// ---------------------------------------------------------------------------
// Current user
// ---------------------------------------------------------------------------

export const CURRENT_USER_ID = "u-self";

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const MOCK_TEAMS: Team[] = [
  {
    id: "t-1",
    name: "AirSend",
    description: "Main product team",
    ownerId: "u-self",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2026-02-25T08:00:00Z",
  },
  {
    id: "t-2",
    name: "Design",
    description: "UI/UX and brand design team",
    ownerId: "u-2",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2026-02-24T12:00:00Z",
  },
  {
    id: "t-3",
    name: "Marketing",
    description: "Growth and marketing team",
    ownerId: "u-3",
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2026-02-20T09:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MOCK_MEMBERS: TeamMember[] = [
  {
    id: "m-1",
    userId: "u-self",
    teamId: "t-1",
    username: "you",
    displayName: "You",
    email: "you@airsend.io",
    role: "owner",
    status: "online",
    joinedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "m-2",
    userId: "u-2",
    teamId: "t-1",
    username: "sarah.chen",
    displayName: "Sarah Chen",
    email: "sarah@airsend.io",
    role: "admin",
    status: "online",
    customStatus: "In a meeting",
    joinedAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "m-3",
    userId: "u-3",
    teamId: "t-1",
    username: "raj.patel",
    displayName: "Raj Patel",
    email: "raj@airsend.io",
    role: "member",
    status: "idle",
    joinedAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "m-4",
    userId: "u-4",
    teamId: "t-1",
    username: "alex.kim",
    displayName: "Alex Kim",
    email: "alex@airsend.io",
    role: "member",
    status: "dnd",
    customStatus: "Focus time",
    joinedAt: "2025-02-15T10:00:00Z",
  },
  {
    id: "m-5",
    userId: "u-5",
    teamId: "t-1",
    username: "diana.taylor",
    displayName: "Diana Taylor",
    email: "diana@airsend.io",
    role: "moderator",
    status: "offline",
    joinedAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "m-6",
    userId: "u-6",
    teamId: "t-1",
    username: "mike.johnson",
    displayName: "Mike Johnson",
    email: "mike@airsend.io",
    role: "member",
    status: "online",
    joinedAt: "2025-04-01T10:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Channels
// ---------------------------------------------------------------------------

export const MOCK_CHANNELS: Channel[] = [
  {
    id: "ch-1",
    teamId: "t-1",
    name: "general",
    description: "General discussion for the team",
    type: "text",
    visibility: "public",
    isPinned: false,
    isDefault: true,
    isLocked: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2026-02-26T01:00:00Z",
    unreadCount: 3,
    lastMessageAt: "2026-02-26T01:00:00Z",
  },
  {
    id: "ch-2",
    teamId: "t-1",
    name: "announcements",
    description: "Important team announcements",
    type: "announcement",
    visibility: "public",
    isPinned: true,
    isDefault: true,
    isLocked: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
    unreadCount: 1,
    lastMessageAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "ch-3",
    teamId: "t-1",
    name: "frontend",
    description: "Frontend development discussions",
    type: "text",
    visibility: "public",
    isPinned: false,
    isDefault: false,
    isLocked: false,
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2026-02-26T00:30:00Z",
    unreadCount: 8,
    lastMessageAt: "2026-02-26T00:30:00Z",
  },
  {
    id: "ch-4",
    teamId: "t-1",
    name: "backend",
    description: "Backend and API discussions",
    type: "text",
    visibility: "public",
    isPinned: false,
    isDefault: false,
    isLocked: false,
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2026-02-25T22:00:00Z",
    unreadCount: 0,
    lastMessageAt: "2026-02-25T22:00:00Z",
  },
  {
    id: "ch-5",
    teamId: "t-1",
    name: "design-review",
    description: "Design reviews and feedback",
    type: "text",
    visibility: "private",
    isPinned: false,
    isDefault: false,
    isLocked: true,
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2026-02-24T16:00:00Z",
    unreadCount: 0,
    lastMessageAt: "2026-02-24T16:00:00Z",
  },
  {
    id: "ch-6",
    teamId: "t-1",
    name: "standup",
    description: "Daily standup voice channel",
    type: "voice",
    visibility: "public",
    isPinned: false,
    isDefault: false,
    isLocked: false,
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2026-02-26T00:00:00Z",
    unreadCount: 0,
  },
  // Design team channels
  {
    id: "ch-d1",
    teamId: "t-2",
    name: "general",
    description: "Design team general",
    type: "text",
    visibility: "public",
    isPinned: false,
    isDefault: true,
    isLocked: false,
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
    unreadCount: 2,
    lastMessageAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "ch-d2",
    teamId: "t-2",
    name: "announcements",
    description: "Design announcements",
    type: "announcement",
    visibility: "public",
    isPinned: true,
    isDefault: true,
    isLocked: false,
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2026-02-24T10:00:00Z",
    unreadCount: 0,
    lastMessageAt: "2026-02-24T10:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

const today = "2026-02-26";
const yesterday = "2026-02-25";

export const MOCK_MESSAGES: ChatMessage[] = [
  // -- Yesterday messages --
  {
    id: "msg-1",
    channelId: "ch-1",
    authorId: "u-2",
    authorName: "Sarah Chen",
    content: "Hey team! I just pushed the new sidebar component. Can someone review the PR?",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T09:15:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: [],
    reactions: [{ emoji: "👍", count: 3, userIds: ["u-3", "u-4", "u-self"] }],
    attachments: [],
    threadReplyCount: 2,
    threadLastReplyAt: `${yesterday}T09:45:00Z`,
    isDeleted: false,
  },
  {
    id: "msg-2",
    channelId: "ch-1",
    authorId: "u-3",
    authorName: "Raj Patel",
    content: "Sure, I'll take a look! Which branch?",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T09:18:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    replyTo: {
      messageId: "msg-1",
      authorId: "u-2",
      authorName: "Sarah Chen",
      content: "Hey team! I just pushed the new sidebar component...",
    },
    mentions: [],
    reactions: [],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
  {
    id: "msg-3",
    channelId: "ch-1",
    authorId: "u-2",
    authorName: "Sarah Chen",
    content: "It's on `feature/sidebar-v2`. @raj.patel thanks!",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T09:20:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: ["u-3"],
    reactions: [],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
  {
    id: "msg-4",
    channelId: "ch-1",
    authorId: "u-4",
    authorName: "Alex Kim",
    content:
      "I've been working on the notification system. Here's the architecture doc I drafted. Let me know your thoughts!",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T14:30:00Z`,
    isEdited: false,
    isPinned: true,
    isPinnedPublic: true,
    mentions: [],
    reactions: [
      { emoji: "🔥", count: 2, userIds: ["u-2", "u-self"] },
      { emoji: "👀", count: 1, userIds: ["u-5"] },
    ],
    attachments: [
      {
        id: "att-1",
        name: "notification-arch.pdf",
        url: "#",
        mimeType: "application/pdf",
        size: 245000,
      },
    ],
    threadReplyCount: 5,
    threadLastReplyAt: `${yesterday}T16:20:00Z`,
    isDeleted: false,
  },
  {
    id: "msg-5",
    channelId: "ch-1",
    authorId: "u-5",
    authorName: "Diana Taylor",
    content:
      "@you @sarah.chen Can we schedule a sync tomorrow to discuss the Q1 roadmap? I have some ideas for the workspace feature.",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T16:45:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: ["u-self", "u-2"],
    reactions: [{ emoji: "✅", count: 2, userIds: ["u-self", "u-2"] }],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
  // -- Today messages --
  {
    id: "msg-6",
    channelId: "ch-1",
    authorId: "u-self",
    authorName: "You",
    content: "Good morning everyone! 🌅 Ready for a productive day.",
    type: "text",
    priority: "normal",
    createdAt: `${today}T08:00:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: [],
    reactions: [
      { emoji: "☀️", count: 3, userIds: ["u-2", "u-3", "u-6"] },
    ],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
  {
    id: "msg-7",
    channelId: "ch-1",
    authorId: "u-6",
    authorName: "Mike Johnson",
    content:
      "Morning! Just deployed the latest build to staging. Everything looks stable. 🚀",
    type: "text",
    priority: "normal",
    createdAt: `${today}T08:15:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: [],
    reactions: [
      { emoji: "🎉", count: 2, userIds: ["u-self", "u-2"] },
    ],
    attachments: [],
    threadReplyCount: 3,
    threadLastReplyAt: `${today}T08:45:00Z`,
    isDeleted: false,
  },
  {
    id: "msg-8",
    channelId: "ch-1",
    authorId: "u-2",
    authorName: "Sarah Chen",
    content:
      "Great work @mike.johnson! I noticed the calendar component had a small rendering issue. Here's a screenshot:",
    type: "text",
    priority: "normal",
    createdAt: `${today}T08:30:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: ["u-6"],
    reactions: [],
    attachments: [
      {
        id: "att-2",
        name: "calendar-issue.png",
        url: "#",
        mimeType: "image/png",
        size: 128000,
        previewUrl: "#",
      },
    ],
    threadReplyCount: 0,
    isDeleted: false,
  },
  {
    id: "msg-9",
    channelId: "ch-1",
    authorId: "u-3",
    authorName: "Raj Patel",
    content:
      "I reviewed the PR @sarah.chen — looks good overall! Left a few comments on the CSS styles. Also, I think we should consider using CSS variables for the theme colors instead of hardcoded values.",
    type: "text",
    priority: "normal",
    createdAt: `${today}T09:00:00Z`,
    isEdited: true,
    editedAt: `${today}T09:05:00Z`,
    isPinned: false,
    isPinnedPublic: false,
    mentions: ["u-2"],
    reactions: [
      { emoji: "💡", count: 1, userIds: ["u-2"] },
    ],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
  // -- Frontend channel messages --
  {
    id: "msg-f1",
    channelId: "ch-3",
    authorId: "u-4",
    authorName: "Alex Kim",
    content:
      "Has anyone tried the new React 19 concurrent features? I'm thinking of implementing `use()` for our data fetching.",
    type: "text",
    priority: "normal",
    createdAt: `${today}T07:00:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: [],
    reactions: [{ emoji: "🤔", count: 2, userIds: ["u-3", "u-6"] }],
    attachments: [],
    threadReplyCount: 4,
    threadLastReplyAt: `${today}T08:30:00Z`,
    isDeleted: false,
  },
  // -- Announcements --
  {
    id: "msg-a1",
    channelId: "ch-2",
    authorId: "u-self",
    authorName: "You",
    content:
      "📢 **Team Update**: We're migrating to the new workspace system next week. Please make sure all your branches are merged by Friday. Check the docs for migration steps.",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T14:00:00Z`,
    isEdited: false,
    isPinned: true,
    isPinnedPublic: true,
    mentions: [],
    reactions: [
      { emoji: "👍", count: 5, userIds: ["u-2", "u-3", "u-4", "u-5", "u-6"] },
    ],
    attachments: [],
    threadReplyCount: 0,
    isDeleted: false,
  },
];

// ---------------------------------------------------------------------------
// Thread replies (for msg-1)
// ---------------------------------------------------------------------------

export const MOCK_THREAD_REPLIES: ChatMessage[] = [
  {
    id: "tr-1",
    channelId: "ch-1",
    authorId: "u-3",
    authorName: "Raj Patel",
    content: "Looking at it now. The layout looks clean!",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T09:30:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: [],
    reactions: [],
    attachments: [],
    threadId: "msg-1",
    threadReplyCount: 0,
    isDeleted: false,
  },
  {
    id: "tr-2",
    channelId: "ch-1",
    authorId: "u-4",
    authorName: "Alex Kim",
    content: "Agreed, nice work @sarah.chen! One suggestion: maybe add a transition on the collapse animation?",
    type: "text",
    priority: "normal",
    createdAt: `${yesterday}T09:45:00Z`,
    isEdited: false,
    isPinned: false,
    isPinnedPublic: false,
    mentions: ["u-2"],
    reactions: [{ emoji: "💯", count: 1, userIds: ["u-2"] }],
    attachments: [],
    threadId: "msg-1",
    threadReplyCount: 0,
    isDeleted: false,
  },
];

// ---------------------------------------------------------------------------
// Direct Messages
// ---------------------------------------------------------------------------

export const MOCK_DMS: DirectMessage[] = [
  {
    id: "dm-1",
    participantIds: ["u-self", "u-2"],
    participants: [
      { userId: "u-self", username: "you", displayName: "You", status: "online" },
      { userId: "u-2", username: "sarah.chen", displayName: "Sarah Chen", status: "online" },
    ],
    lastMessage: {
      id: "dm-msg-1",
      channelId: "dm-1",
      authorId: "u-2",
      authorName: "Sarah Chen",
      content: "Can you check the PR when you get a chance?",
      type: "text",
    priority: "normal",
      createdAt: `${today}T08:45:00Z`,
      isEdited: false,
      isPinned: false,
      isPinnedPublic: false,
      mentions: [],
      reactions: [],
      attachments: [],
      threadReplyCount: 0,
      isDeleted: false,
    },
    unreadCount: 1,
    updatedAt: `${today}T08:45:00Z`,
  },
  {
    id: "dm-2",
    participantIds: ["u-self", "u-3"],
    participants: [
      { userId: "u-self", username: "you", displayName: "You", status: "online" },
      { userId: "u-3", username: "raj.patel", displayName: "Raj Patel", status: "idle" },
    ],
    lastMessage: {
      id: "dm-msg-2",
      channelId: "dm-2",
      authorId: "u-self",
      authorName: "You",
      content: "Sounds good, let's sync tomorrow.",
      type: "text",
    priority: "normal",
      createdAt: `${yesterday}T17:30:00Z`,
      isEdited: false,
      isPinned: false,
      isPinnedPublic: false,
      mentions: [],
      reactions: [],
      attachments: [],
      threadReplyCount: 0,
      isDeleted: false,
    },
    unreadCount: 0,
    updatedAt: `${yesterday}T17:30:00Z`,
  },
];

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export const MOCK_NOTIFICATIONS: ChatNotification[] = [
  {
    id: "n-1",
    type: "mention",
    teamId: "t-1",
    channelId: "ch-1",
    messageId: "msg-5",
    fromUserId: "u-5",
    fromUserName: "Diana Taylor",
    content: "mentioned you in #general",
    isRead: false,
    createdAt: `${yesterday}T16:45:00Z`,
  },
  {
    id: "n-2",
    type: "reply",
    teamId: "t-1",
    channelId: "ch-1",
    messageId: "msg-7",
    fromUserId: "u-6",
    fromUserName: "Mike Johnson",
    content: "replied to a thread you're following",
    isRead: false,
    createdAt: `${today}T08:45:00Z`,
  },
  {
    id: "n-3",
    type: "dm",
    teamId: "t-1",
    messageId: "dm-msg-1",
    fromUserId: "u-2",
    fromUserName: "Sarah Chen",
    content: "sent you a direct message",
    isRead: false,
    createdAt: `${today}T08:45:00Z`,
  },
  {
    id: "n-4",
    type: "reaction",
    teamId: "t-1",
    channelId: "ch-1",
    messageId: "msg-6",
    fromUserId: "u-3",
    fromUserName: "Raj Patel",
    content: "reacted ☀️ to your message",
    isRead: true,
    createdAt: `${today}T08:10:00Z`,
  },
];

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

export const MOCK_TASKS: ChatTask[] = [
  {
    id: "task-1",
    title: "Review sidebar PR #234",
    description: "Review Sarah's sidebar component PR",
    assigneeId: "u-self",
    teamId: "t-1",
    channelId: "ch-3",
    status: "in-progress",
    priority: "high",
    dueDate: `${today}T17:00:00Z`,
    createdAt: `${yesterday}T09:00:00Z`,
  },
  {
    id: "task-2",
    title: "Update notification system docs",
    assigneeId: "u-self",
    teamId: "t-1",
    status: "todo",
    priority: "medium",
    dueDate: "2026-02-28T17:00:00Z",
    createdAt: `${yesterday}T14:30:00Z`,
  },
  {
    id: "task-3",
    title: "Fix calendar rendering bug",
    description: "Calendar shows wrong date on mobile",
    assigneeId: "u-self",
    teamId: "t-1",
    channelId: "ch-3",
    status: "todo",
    priority: "urgent",
    dueDate: `${today}T12:00:00Z`,
    createdAt: `${today}T08:30:00Z`,
  },
];
