import type {
    IOrganization,
    IDomain,
    IDomainOrgHistory,
    IMember,
    IRole,
    ILog,
    IAccountSettings,
} from "./types"

// ─── Domains (defined first so organizations can reference them) ─
export const MOCK_DOMAINS: IDomain[] = [
    {
        id: "dom_001",
        domain_name: "acme.com",
        org_id: "org_001",
        org_name: "Acme Corporation",
        status: "active",
        dns_verified: true,
        mx_verified: true,
        spf_verified: true,
        dkim_verified: true,
        dmarc_verified: true,
        accounts_count: 45,
        created_at: "2024-06-15T10:05:00Z",
        updated_at: "2025-01-20T08:30:00Z",
    },
    {
        id: "dom_002",
        domain_name: "acme.org",
        org_id: "org_001",
        org_name: "Acme Corporation",
        status: "active",
        dns_verified: true,
        mx_verified: true,
        spf_verified: true,
        dkim_verified: false,
        dmarc_verified: true,
        accounts_count: 12,
        created_at: "2024-08-20T11:30:00Z",
        updated_at: "2025-01-15T09:00:00Z",
    },
    {
        id: "dom_003",
        domain_name: "techstart.io",
        org_id: "org_002",
        org_name: "TechStart Inc",
        status: "active",
        dns_verified: true,
        mx_verified: true,
        spf_verified: true,
        dkim_verified: true,
        dmarc_verified: true,
        accounts_count: 28,
        created_at: "2024-09-01T14:10:00Z",
        updated_at: "2025-02-10T11:00:00Z",
    },
    {
        id: "dom_004",
        domain_name: "techstart.dev",
        org_id: "org_002",
        org_name: "TechStart Inc",
        status: "pending",
        dns_verified: true,
        mx_verified: false,
        spf_verified: false,
        dkim_verified: false,
        dmarc_verified: false,
        accounts_count: 0,
        created_at: "2025-02-20T16:00:00Z",
        updated_at: "2025-02-20T16:00:00Z",
    },
    {
        id: "dom_005",
        domain_name: "globalsolutions.co.uk",
        org_id: "org_003",
        org_name: "Global Solutions Ltd",
        status: "active",
        dns_verified: true,
        mx_verified: true,
        spf_verified: true,
        dkim_verified: true,
        dmarc_verified: false,
        accounts_count: 60,
        created_at: "2025-01-05T09:10:00Z",
        updated_at: "2025-02-25T16:45:00Z",
    },
    {
        id: "dom_006",
        domain_name: "demo-mail.xyz",
        org_id: null,
        org_name: null,
        status: "inactive",
        dns_verified: false,
        mx_verified: false,
        spf_verified: false,
        dkim_verified: false,
        dmarc_verified: false,
        accounts_count: 2,
        created_at: "2025-02-01T08:00:00Z",
        updated_at: "2025-02-01T08:00:00Z",
    },
]

// ─── Organizations (OrganizationEntity) ─────────────────────────
export const MOCK_ORGANIZATIONS: IOrganization[] = [
    {
        id: "org_001",
        name: "Acme Corporation",
        title: "Acme Corp",
        phone: "+1-555-100-2000",
        address: "100 Innovation Drive, San Francisco, CA 94107",
        report_email: "reports@acme.com",
        logo_url: null,
        bimi_record: null,
        settings: {},
        domains: MOCK_DOMAINS.filter((d) => d.org_id === "org_001"),
        created_by: "admin@acme.com",
        created_at: "2024-06-15T10:00:00Z",
        updated_at: "2025-01-20T08:30:00Z",
    },
    {
        id: "org_002",
        name: "TechStart Inc",
        title: "TechStart",
        phone: "+1-555-200-3000",
        address: "250 Startup Blvd, Austin, TX 78701",
        report_email: "ops@techstart.io",
        logo_url: null,
        bimi_record: null,
        settings: {},
        domains: MOCK_DOMAINS.filter((d) => d.org_id === "org_002"),
        created_by: "cto@techstart.io",
        created_at: "2024-09-01T14:00:00Z",
        updated_at: "2025-02-10T11:00:00Z",
    },
    {
        id: "org_003",
        name: "Global Solutions Ltd",
        title: "Global Solutions",
        phone: "+44-20-7946-0958",
        address: "10 Downing Street, London EC1A 1BB",
        report_email: "admin@globalsolutions.co.uk",
        logo_url: null,
        bimi_record: null,
        settings: {},
        domains: MOCK_DOMAINS.filter((d) => d.org_id === "org_003"),
        created_by: "owner@globalsolutions.co.uk",
        created_at: "2025-01-05T09:00:00Z",
        updated_at: "2025-02-25T16:45:00Z",
    },
]

// ─── Domain-Org History (DomainOrgHistoryEntity) ────────────────
export const MOCK_DOMAIN_HISTORY: IDomainOrgHistory[] = [
    {
        id: "doh_001",
        domain_id: "dom_001",
        org_id: "org_001",
        assigned_at: "2024-06-15T10:05:00Z",
        revoked_at: null,
        changed_by: "admin@acme.com",
        domain_name: "acme.com",
        org_name: "Acme Corporation",
    },
    {
        id: "doh_002",
        domain_id: "dom_006",
        org_id: "org_002",
        assigned_at: "2025-01-10T09:00:00Z",
        revoked_at: "2025-02-01T08:00:00Z",
        changed_by: "cto@techstart.io",
        domain_name: "demo-mail.xyz",
        org_name: "TechStart Inc",
    },
]

// ─── Members ────────────────────────────────────────────────────
export const MOCK_MEMBERS: IMember[] = [
    {
        id: "mem_001",
        name: "John Doe",
        email: "john@acme.com",
        role: "Owner",
        organization: "Acme Corporation",
        org_id: "org_001",
        domain: "acme.com",
        status: "active",
        avatar_url: null,
        joined_at: "2024-06-15T10:00:00Z",
        last_active: "2026-02-26T08:30:00Z",
    },
    {
        id: "mem_002",
        name: "Jane Smith",
        email: "jane@acme.com",
        role: "Administrator",
        organization: "Acme Corporation",
        org_id: "org_001",
        domain: "acme.com",
        status: "active",
        avatar_url: null,
        joined_at: "2024-07-01T09:00:00Z",
        last_active: "2026-02-25T17:45:00Z",
    },
    {
        id: "mem_003",
        name: "Mike Johnson",
        email: "mike@acme.org",
        role: "Member",
        organization: "Acme Corporation",
        org_id: "org_001",
        domain: "acme.org",
        status: "active",
        avatar_url: null,
        joined_at: "2024-10-12T14:00:00Z",
        last_active: "2026-02-24T11:20:00Z",
    },
    {
        id: "mem_004",
        name: "Sarah Wilson",
        email: "sarah@techstart.io",
        role: "Owner",
        organization: "TechStart Inc",
        org_id: "org_002",
        domain: "techstart.io",
        status: "active",
        avatar_url: null,
        joined_at: "2024-09-01T14:00:00Z",
        last_active: "2026-02-26T09:15:00Z",
    },
    {
        id: "mem_005",
        name: "Alex Kim",
        email: "alex@techstart.io",
        role: "Member",
        organization: "TechStart Inc",
        org_id: "org_002",
        domain: "techstart.io",
        status: "active",
        avatar_url: null,
        joined_at: "2024-11-05T10:00:00Z",
        last_active: "2026-02-23T16:00:00Z",
    },
    {
        id: "mem_006",
        name: "Emily Brown",
        email: "emily@globalsolutions.co.uk",
        role: "Administrator",
        organization: "Global Solutions Ltd",
        org_id: "org_003",
        domain: "globalsolutions.co.uk",
        status: "active",
        avatar_url: null,
        joined_at: "2025-01-10T11:00:00Z",
        last_active: "2026-02-25T14:30:00Z",
    },
    {
        id: "mem_007",
        name: "Tom Baker",
        email: "tom@acme.com",
        role: "Viewer",
        organization: "Acme Corporation",
        org_id: "org_001",
        domain: "acme.com",
        status: "banned",
        avatar_url: null,
        joined_at: "2025-01-15T08:00:00Z",
        last_active: "2025-12-20T10:00:00Z",
    },
    {
        id: "mem_008",
        name: "Priya Patel",
        email: "priya@globalsolutions.co.uk",
        role: "Member",
        organization: "Global Solutions Ltd",
        org_id: "org_003",
        domain: "globalsolutions.co.uk",
        status: "invited",
        avatar_url: null,
        joined_at: "2026-02-20T09:00:00Z",
        last_active: "2026-02-20T09:00:00Z",
    },
]

// ─── Roles ──────────────────────────────────────────────────────
export const MOCK_ROLES: IRole[] = [
    {
        id: "role_001",
        name: "Super Admin",
        description: "Full system access — can only be assigned to the org owner.",
        permissions: ["read", "write", "admin", "delete", "manage_users", "manage_settings", "manage_billing", "manage_domains", "view_logs", "manage_roles"],
        is_default: false,
        is_system: true,
        user_count: 1,
        created_at: "2024-06-15T10:00:00Z",
    },
    {
        id: "role_002",
        name: "Administrator",
        description: "Full organization management access except billing.",
        permissions: ["read", "write", "admin", "manage_users", "manage_settings", "manage_domains", "view_logs"],
        is_default: false,
        is_system: true,
        user_count: 3,
        created_at: "2024-06-15T10:00:00Z",
    },
    {
        id: "role_003",
        name: "Member",
        description: "Standard user with read/write access.",
        permissions: ["read", "write"],
        is_default: true,
        is_system: true,
        user_count: 18,
        created_at: "2024-06-15T10:00:00Z",
    },
    {
        id: "role_004",
        name: "Viewer",
        description: "Read-only access to the organization.",
        permissions: ["read"],
        is_default: false,
        is_system: true,
        user_count: 5,
        created_at: "2024-06-15T10:00:00Z",
    },
    {
        id: "role_005",
        name: "Support Agent",
        description: "Can view logs and manage user tickets.",
        permissions: ["read", "view_logs", "manage_users"],
        is_default: false,
        is_system: false,
        user_count: 2,
        created_at: "2025-03-10T12:00:00Z",
    },
]

// ─── Logs ───────────────────────────────────────────────────────
export const MOCK_LOGS: ILog[] = [
    {
        id: "log_001",
        timestamp: "2026-02-26T10:30:25Z",
        level: "info",
        message: "User admin@acme.com logged in successfully",
        source: "auth",
        actor: "admin@acme.com",
        org_id: "org_001",
        metadata: null,
    },
    {
        id: "log_002",
        timestamp: "2026-02-26T10:28:15Z",
        level: "warn",
        message: "Failed login attempt for user@acme.com (3rd try)",
        source: "auth",
        actor: "user@acme.com",
        org_id: "org_001",
        metadata: { attempts: 3 },
    },
    {
        id: "log_003",
        timestamp: "2026-02-26T10:25:10Z",
        level: "error",
        message: "SMTP relay timeout for techstart.io — retried 2 times",
        source: "smtp",
        actor: "system",
        org_id: "org_002",
        metadata: { retries: 2 },
    },
    {
        id: "log_004",
        timestamp: "2026-02-26T10:20:05Z",
        level: "info",
        message: 'Organization "Global Solutions Ltd" settings updated',
        source: "system",
        actor: "emily@globalsolutions.co.uk",
        org_id: "org_003",
        metadata: null,
    },
    {
        id: "log_005",
        timestamp: "2026-02-26T10:15:00Z",
        level: "info",
        message: "Domain techstart.dev added — pending DNS verification",
        source: "domains",
        actor: "sarah@techstart.io",
        org_id: "org_002",
        metadata: { domain: "techstart.dev" },
    },
    {
        id: "log_006",
        timestamp: "2026-02-26T10:12:00Z",
        level: "info",
        message: "Member priya@globalsolutions.co.uk invited",
        source: "members",
        actor: "emily@globalsolutions.co.uk",
        org_id: "org_003",
        metadata: null,
    },
    {
        id: "log_007",
        timestamp: "2026-02-26T10:05:00Z",
        level: "warn",
        message: "SPF record mismatch on acme.org — emails may land in spam",
        source: "dns",
        actor: "system",
        org_id: "org_001",
        metadata: { domain: "acme.org" },
    },
    {
        id: "log_008",
        timestamp: "2026-02-26T09:55:00Z",
        level: "debug",
        message: "Auto-sync completed for acme.com (45 accounts)",
        source: "sync",
        actor: "system",
        org_id: "org_001",
        metadata: { accounts: 45, duration_ms: 2340 },
    },
    {
        id: "log_009",
        timestamp: "2026-02-26T09:50:00Z",
        level: "error",
        message: "DKIM signing failure for demo-mail.xyz — key expired",
        source: "dkim",
        actor: "system",
        org_id: null,
        metadata: { domain: "demo-mail.xyz" },
    },
    {
        id: "log_010",
        timestamp: "2026-02-26T09:40:00Z",
        level: "info",
        message: "Role \"Support Agent\" created by admin@acme.com",
        source: "roles",
        actor: "admin@acme.com",
        org_id: "org_001",
        metadata: { role_id: "role_005" },
    },
]

// ─── Default Account Settings (from MailsAccountsSettingsEntity defaults) ──
export const DEFAULT_ACCOUNT_SETTINGS: IAccountSettings = {
    notifications: { new_email: true, delivery_failed: false, delivery_success: false, undelivered_email: false, push_notification: false },
    security: { password_confirmation: false, password_expiration: { enabled: false, days: 0 }, change_on_first_login: false },
    blocked_sent_domain: [],
    blocked_recepient_domain: [],
    aliases: [],
    forwarding_rules: [],
    catch_emails: [],
    smtp_config: { enable_smtp: true, enable_smtp_from_alias: false, allow_email_tracking: false },
    auto_reply: { enabled: false, ON_NEW_MESSAGE: {}, ON_REPLY_MESSAGE: {} },
    vacationSender: { enabled: false, message: "", startDate: "", endDate: "" },
    user: { display_name: null, first_name: null, last_name: null, use_display_name: true, timezone: "Asia/Kolkata" },
    personalization: { theme: "dark", layout: "2-column" },
    email_settings: {
        autoShowImages: false, keepMessages: true, excludeSpam: true, confirmLinks: true,
        conversationGrouping: true, autoDeleteUnwanted: false, stickyLabels: false,
        monthly_limit: 1000, thresold_limit: 500, secure_email_enabled: true,
        email_footer: { footer_enabled: false, footer_text: null },
        system_email: { is_system_email: false, system_email_reply: null },
    },
    email_privacy: { autoShowImages: false, block_email_tracking: false },
    imap_config: { enable_imap: false },
    calender_config: { enable_calender: false },
    display: { showMeetings: true, showRightSidebar: true, showCalendar: true, showQuota: true, settings: true },
    auto_sync: { enabled: true, interval: 5 },
    signatures: [],
    sieve_filters: {},
    last_synced_at: null,
    sync_error: null,
    sync_status: null,
}
